package it.polimi.ingsw.galaxytruckerproject.network.SOCKET.message;

public enum MessageType {

    //START_GAME phase messages
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    SET_COLOR_REQUEST,
    SET_COLOR_RESPONSE,
    SET_NUMBER_OF_PLAYERS_REQUEST,
    SET_NUMBER_OF_PLAYERS_RESPONSE,
    SHOW_GAMES_LIST_MESSAGE,
    JOIN_GAME_REQUEST,
    CREATE_GAME_REQUEST,
    LEAVE_GAME_MESSAGE,

    //SHIPS_CREATION phase messages
    DRAW_TILE_REQUEST,
    DRAW_TILE_FROM_STACK_REQUEST,
    DRAW_TILE_FROM_TURNED_REQUEST,
    DRAW_TILE_FROM_BOOKED_REQUEST,
    DRAWN_TILE_RESPONSE,
    SET_TILE_REQUEST,
    BOOK_TILE_REQUEST,
    SHOW_TURNED_TILES_REQUEST,
    SHOW_BOOKED_TILES_REQUEST,
    TURN_HOURGLASS_REQUEST,
    SHOW_CARDS_REQUEST,
    END_SHIP_CREATION,

    //DRAW_CARD phase messages
    DRAW_CARD_REQUEST,
    DRAW_CARD_RESPONSE,
    EARLY_LANDING_REQUEST,

    //CARD_EVENT phase messages
    ROLL_THE_DICES_REQUEST,
    ROLL_THE_DICES_RESPONSE,
    PLANET_CHOICE_REQUEST,
    PLANET_CHOICE_RESPONSE,
    MANAGE_GOODS_REQUEST,
    MANAGE_GOODS_RESPONSE,
    USE_CANNON_RESPONSE,
    USE_ENGINE_RESPONSE,

    //Messages used in multiples phases
    SEND_COORDINATES_RESPONSE,
    USE_CANNON_RESPONSE,
    USE_ENGINE_RESPONSE,
    REFUSE_MESSAGE,
    ACCEPT_MESSAGE,
    SHOW_PLAYERS_SHIPBOARD_REQUEST,
    SHOW_PLAYERS_SHIPBOARD_RESPONSE,

    //GENERICS messages
    GENERIC_MESSAGE,
    ERROR_MESSAGE,
    //PING_MESSAGE,
    PLAYERS_LIST,

    //Update light model messages
    UPDATE_DRAWN_CARD,
    UPDATE_SHIPBOARD
}
