package it.polimi.ingsw.galaxytruckerproject.client;

public enum ClientState {
    COORD_REQUEST,MANAGE_GOODS,ACTION,LOBBY,S_END_DRAW_TILE_CARD,MANAGE_CARDS,S_MANAGE_DRAWN_TILE,S_FINISHED,WAIT_OTHER_PLAYER_ACTION
}
