package it.polimi.ingsw.galaxytruckerproject.client;

public enum ClientState {
    CHOOSE_UI,CHOOSE_CONNECTION_TYPE,LOBBY,LOGIN,COLOR_CHOICE,ACTION,COORD_REQUEST,MANAGE_GOODS,PLANET_CHOICE,START_SHIP_CREATION,S_END_DRAW_TILE_CARD,S_MANAGE_CARDS,S_MANAGE_DRAWN_TILE,S_FINISHED,WAIT_OTHER_PLAYER_ACTION
}
